apiVersion: v1
kind: Service
metadata:
  name: wsrestproducto
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert:  arn:aws:acm:us-east-2:887482798966:certificate/e1d649ba-6e3a-496d-a3d4-f38a0672f75c
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  namespace: dev
spec:
  ports:
    - port: 3010
      name: http
      targetPort: 3010
      protocol: TCP
    - port: 443      
      name: https
      targetPort: 3010
      protocol: TCP
  type: LoadBalancer    
  selector:
    app: wsrestproducto
